# Generated by Django 3.2.5 on 2021-07-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(2, '未知'), (1, '男'), (0, '女')], default=2, verbose_name='性别')),
                ('idcard', models.CharField(max_length=18, unique=True, verbose_name='身份证号码')),
                ('phone', models.CharField(max_length=14, verbose_name='手机号')),
                ('imgUrl', models.CharField(max_length=914, verbose_name='照片')),
                ('isCheck', models.BooleanField(default=False, verbose_name='已审核')),
                ('check_time', models.DateTimeField(verbose_name='审核时间')),
                ('company', models.CharField(max_length=256, verbose_name='工作单位名称')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '入场登记管理',
                'verbose_name_plural': '入场登记管理',
            },
        ),
    ]
