# Generated by Django 3.2.5 on 2021-07-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldpersonnel',
            name='check_time',
            field=models.DateTimeField(null=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='fieldpersonnel',
            name='isCheck',
            field=models.BooleanField(default=False, null=True, verbose_name='已审核'),
        ),
        migrations.AlterField(
            model_name='fieldpersonnel',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (0, '女'), (2, '未知')], default=2, verbose_name='性别'),
        ),
    ]
