# Generated by Django 3.2.5 on 2021-07-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourceapp', '0002_auto_20210703_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('idcard', models.CharField(max_length=18, verbose_name='身份证号码')),
                ('phone', models.CharField(max_length=14, verbose_name='手机号')),
                ('company', models.CharField(max_length=256, verbose_name='工作单位名称')),
                ('check_time', models.DateTimeField(null=True, verbose_name='审核时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '请假登记管理',
                'verbose_name_plural': '请假登记管理',
            },
        ),
        migrations.AlterField(
            model_name='fieldpersonnel',
            name='idcard',
            field=models.CharField(max_length=18, verbose_name='身份证号码'),
        ),
    ]
