# Generated by Django 3.2.5 on 2021-07-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourceapp', '0003_auto_20210707_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecheck',
            name='isCheck',
            field=models.BooleanField(default=False, null=True, verbose_name='已审核'),
        ),
    ]
