# Generated by Django 3.2.5 on 2021-07-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourceapp', '0004_leavecheck_ischeck'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffSiteCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('phone', models.CharField(max_length=14, verbose_name='手机号')),
                ('check_time', models.DateTimeField(null=True, verbose_name='审核时间')),
                ('isCheck', models.BooleanField(default=False, null=True, verbose_name='已审核')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '离场登记管理',
                'verbose_name_plural': '离场登记管理',
            },
        ),
        migrations.AddField(
            model_name='fieldpersonnel',
            name='fieldNum',
            field=models.IntegerField(default=1, verbose_name='进场次数'),
        ),
        migrations.AddField(
            model_name='fieldpersonnel',
            name='personState',
            field=models.BooleanField(default=True, null=True, verbose_name='是否在现场'),
        ),
    ]
